### ISSUE TITLE
invalid argument when running example/main.go

### ISSUE THREAD

**Issue by lianoid** [daulet/tokenizers#20] opened 2024-07-02 04:18 UTC
I have compiled the project through make build, and put the compiled libtokenizers.a file in the root directory of tokenizers project.

I can run all the test cases in tokenizer_test.go normally through _go test_.

But when I run example, the program can read libtokenizers.a correctly, but it will report an error when I run example use cmd ```go run main.go```:

```bash
panic: invalid argument

goroutine 1 [running]:
main.main()
        /search/odin/liliang/tokenizers-0.7.1/example/main.go:12 +0x2f2
exit status 2
```

I've tried master/v0.7.1/v0.8.0/v0.60.0, and they all have the same problem.

My golang version info is: _go version go1.22.0 linux/amd64_

**Comment by daulet** [comment] 2024-07-06 12:03
@lianoid you are probably missing a build parameter `-ldflags="-extldflags '-L./'"`, which is required in latest release to hint the linker where the native library is.

**Comment by lianoid** [comment] 2024-07-08 03:28
@daulet Thank you for your answer.
I tried to add the parameters you mentioned and went to go run, but the program still reported the same error.
I use `tokenizers.FromBytes(bertBaseTokenizeModelData) `instead of `tokenizers.FromFile("./test/data/bert-base-uncased.json")` to solve this problem.

And I tried to run 
```go
	tk1, err1 := tokenizers.FromBytes(bertBaseTokenizeModelData)
	if err1 != nil {
		panic(err1)
	}
	// release native resources
	defer tk1.Close()

	tk, err := tokenizers.FromFile("./test/data/bert-base-uncased.json")
	if err != nil {
		panic(err)
	}
	// release native resources
	defer tk.Close()

	fmt.Println("Test2 Vocab size:", tk.VocabSize())
	// Vocab size: 30522
	fmt.Println(tk.Encode("brown fox jumps over the lazy dog", false))
```
And the Tokenizer `tk` loaded by`FromFile` can also Encode normally, but after I removed the loading of `tk1`, I reported the previous `invalid argument` error, although it sounds incredible.

**Comment by daulet** [comment] 2024-07-09 08:01
can you paste the whole program you are trying to run, and the error you are getting? It's unclear what exactly is failing in your case.

**Comment by davidliudev** [comment] 2024-07-31 09:45
I have the same issue: invalid argument.
The workaround above of using FromBytes instead of FromFile fixes the issue for now. 

Looks like there are issues in FromFile

**Comment by daulet** [comment] 2024-08-04 04:39
There are tests for `FromFile` in the module, so it is not completely broken. To make progress someone needs to share a full repro.

**Comment by cckate** [comment] 2024-08-20 06:28
Kind of have the same problem when using `FromFile` function. This err `invalid argument` is really interesting. It seems like it was missing something in `FromFile`

**Comment by daulet** [comment] 2024-08-21 20:57
I'll close the issue until folks provide a repro. I trust there is an issue, but no one is sharing repro and I couldn't repro.

**Closed by daulet** 2024-08-21 20:57 UTC

**Comment by lwabish** [comment] 2025-02-25 13:44
Met this when integrating `tokenizers.Fromfile()` into my go server.
But the weird thing is this error only show up in one of our many environments. I am running my server in docker and have no idea how to debug this. If you are still interesting in this, maybe I can help collect some environment related info of reproduct this error.

**Comment by daulet** [comment] 2025-02-25 16:08
can you paste (1) your stack trace, (2) version of this library, (3) `uname -a` on the machine you built it and running it

**Comment by daulet** [comment] 2025-02-25 17:28
@lwabish ^

**Comment by lwabish** [comment] 2025-02-26 02:50
My code looks like this:
```go
func NewTokenizer(filepath string ... ...) (*Tokenizer, error) {
        tokenizer, err := tokenizers.FromFile(filepath)
if err != nil {
			return nil, fmt.Errorf("failed to load tokenizer from %s: %w", filepath, err)
		}
... ...
}
```

The error is simple: basiclly `invalid argument` with some other wrapped error
```
failed to load tokenizer from /tokenizers/*******/tokenizer.json: invalid argument
```

go mod version:
```
github.com/daulet/tokenizers v0.7.0
```

the `cargo build --release` command to build `libtokenizers.a` is run on commit https://github.com/daulet/tokenizers/commit/8531b2b902c0a5f0092c6f2214cf16657091f3b7

the container running env:
```
NAME="CentoS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

Linux jtbb-damoxing-poc-ly 3.10.0-1160.114.2.el7.x86_64 #1 SMP Wed Mar 20 15:54:52 UTC 2024 x86_64 x86_64 x86_64
```

the building env is containerized with following dockerfile
```Dockerfile
FROM rust:1.75 as tk

COPY . third_party/tokenizers

RUN cd third_party/tokenizers && cargo build --release
```

```Dockerfile
...
COPY --from=tk third_party/tokenizers/target/release/libtokenizers.a /go/pkg/mod/github.com/daulet/tokenizers@v0.7.0
RUN GOOS=linux go build -o /xxxxxx -ldflags '-linkmode external -w -extldflags "-static"' ./main.go
...
```

@daulet Tell me if further information is needed.

**Comment by lwabish** [comment] 2025-02-26 05:11
FYI：switch to FromBytes did solve this problem
